users:
  Christ:
    username: christ
    articleIds:
      - 1
    commentIds: []
  Hana:
    username: Hana
    articleIds:
      - 2
      - 3
      - 4
    commentIds:
      - 1
  Baller:
    username: Baller
    articleIds:
      - 3
    commentIds:
      - 2
      - 2
      - 3
      - 4
articles:
  '1':
    id: 1
    title: bad
    url: 'http://www.google.com'
    username: asdb
    commentIds: []
    upvotedBy: []
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: Title
    url: 'http://google.com'
    username: mdol
    commentIds:
      - 1
      - 2
      - 2
    upvotedBy: []
    downvotedBy:
      - mdol
    comments:
      - &ref_0
        id: 1
        body: Hi
        username: mdol
        articleId: 2
        upvotedBy: []
        downvotedBy: []
      - id: 2
        body: This is a comment! I love chess
        username: Baller
        articleId: 3
        upvotedBy: []
        downvotedBy: []
  '3':
    id: 3
    title: When ever you are here
    url: 'http://www.google.com'
    username: Hana
    commentIds:
      - 3
    upvotedBy: []
    downvotedBy:
      - Hana
  '4':
    id: 4
    title: Four the floor I was sure
    url: 'http://www.google.com'
    username: Hana
    commentIds:
      - 4
    upvotedBy:
      - Hana
    downvotedBy: []
nextArticleId: 3
comments:
  '1': *ref_0
  '2':
    id: 2
    body: Naughty David!
    username: Baller
    articleId: 2
    upvotedBy: []
    downvotedBy: []
  '3':
    id: 3
    body: Hi
    username: Baller
    articleId: 2
    upvotedBy: []
    downvotedBy: []
  '4':
    id: 4
    body: Here
    username: Baller
    articleId: 2
    upvotedBy: []
    downvotedBy: []
nextCommentId: 2
